SET PATH SYSTEM PATH, USER, UTILS;
VALUES PCRE_SEARCH('FOO', 'FOOBAR');
VALUES PCRE_SEARCH('BAR', 'FOOBAR');
VALUES PCRE_SEARCH('BAZ', 'FOOBAR');
VALUES PCRE_SEARCH('\b\d{1,3}(\.\d{1,3}){3}\b', '192.168.0.1');
VALUES PCRE_SEARCH('<([A-Z][A-Z0-9]*)[^>]*>.*?</\1>', '<B>BOLD!</B>');
VALUES PCRE_SEARCH('Q(?!U)', 'QUACK');
VALUES PCRE_SEARCH('Q(?!U)', 'QI');

VALUES PCRE_SUB('FOO', '\0', 'FOOBAR');
VALUES PCRE_SUB('FOO(BAR)?', '\0', 'FOOBAR');
VALUES PCRE_SUB('BAZ', '\0', 'FOOBAR');
VALUES PCRE_SUB('\b(\d{1,3}(\.\d{1,3}){3})\b', '\1', 'IP address: 192.168.0.1');
VALUES PCRE_SUB('<([A-Z][A-Z0-9]*)[^>]*>(.*?)</\1>', '<I>\2</I>', '<B>BOLD!</B>');
VALUES PCRE_SUB('Q(?!U)', '\0', 'QUACK');
VALUES PCRE_SUB('Q(?!U)', '\0', 'QI');

SELECT *
FROM TABLE(
	PCRE_GROUPS('(FOO)?(\s?)(BAR)?(\s?)(BAZ)?', 'FOOBAR')
);

SELECT ELEMENT, CASE WHEN LEFT(CONTENT, 1) = '"' THEN SUBSTR(CONTENT, 2, LENGTH(CONTENT) - 2) ELSE CONTENT END AS CONTENT
FROM TABLE(
	PCRE_SPLIT('([^",][^,]*|"[^"]*")', '"Some",CSV,",data"')
)
WHERE SEPARATOR = 1;
