CREATE TABLE FOO (
    ID INTEGER NOT NULL PRIMARY KEY,
    VALUE INTEGER NOT NULL
)!

CALL CREATE_EXCEPTION_TABLE('FOO')!
CALL ASSERT_TABLE_EXISTS('FOO_EXCEPTIONS')!
VALUES ASSERT_EQUALS(4, (SELECT COUNT(*) FROM (
    SELECT COLNO, COLNAME
    FROM SYSCAT.COLUMNS
    WHERE TABSCHEMA = CURRENT SCHEMA
    AND TABNAME = 'FOO_EXCEPTIONS'

    INTERSECT

    VALUES
        (0, 'ID'),
        (1, 'VALUE'),
        (2, 'EXCEPT_TS'),
        (3, 'EXCEPT_MSG')
    ) AS T))!

CALL CREATE_EXCEPTION_VIEW('FOO_EXCEPTIONS')!
CALL ASSERT_TABLE_EXISTS('FOO_EXCEPTIONS_V')!
VALUES ASSERT_EQUALS(5, (SELECT COUNT(*) FROM (
    SELECT COLNO, COLNAME
    FROM SYSCAT.COLUMNS
    WHERE TABSCHEMA = CURRENT SCHEMA
    AND TABNAME = 'FOO_EXCEPTIONS_V'

    INTERSECT

    VALUES
        (0, 'ID'),
        (1, 'VALUE'),
        (2, 'EXCEPT_TYPE'),
        (3, 'EXCEPT_OBJECT'),
        (4, 'EXCEPT_TS')
    ) AS T))!

-- XXX Check validity of EXCEPT_MSG conversion

DROP VIEW FOO_EXCEPTIONS_V!
DROP TABLE FOO_EXCEPTIONS!
DROP TABLE FOO!
