VALUES ASSERT_IS_NULL(PCRE_SEARCH('FOO', NULL))!
VALUES ASSERT_EQUALS(PCRE_SEARCH('FOO', 'FOOBAR'), 1)!
VALUES ASSERT_EQUALS(PCRE_SEARCH('BAR', 'FOOBAR'), 4)!
VALUES ASSERT_EQUALS(PCRE_SEARCH('BAZ', 'FOOBAR'), 0)!
VALUES ASSERT_EQUALS(PCRE_SEARCH('\b\d{1,3}(\.\d{1,3}){3}\b', '192.168.0.1'), 1)!
VALUES ASSERT_EQUALS(PCRE_SEARCH('<([A-Z][A-Z0-9]*)[^>]*>.*?</\1>', '<B>BOLD!</B>'), 1)!
VALUES ASSERT_EQUALS(PCRE_SEARCH('Q(?!U)', 'QUACK'), 0)!
VALUES ASSERT_EQUALS(PCRE_SEARCH('Q(?!U)', 'QI'), 1)!

VALUES ASSERT_IS_NULL(PCRE_SUB('BAZ', '\0', 'FOOBAR'))!
VALUES ASSERT_IS_NULL(PCRE_SUB('Q(?!U)', '\0', 'QUACK'))!
VALUES ASSERT_EQUALS(PCRE_SUB('FOO', '\0', 'FOOBAR'), 'FOO')!
VALUES ASSERT_EQUALS(PCRE_SUB('FOO(BAR)?', '\0', 'FOOBAR'), 'FOOBAR')!
VALUES ASSERT_EQUALS(PCRE_SUB('\b(\d{1,3}(\.\d{1,3}){3})\b', '\1', 'IP address: 192.168.0.1'), '192.168.0.1')!
VALUES ASSERT_EQUALS(PCRE_SUB('<([A-Z][A-Z0-9]*)[^>]*>(.*?)</\1>', '<I>\2</I>', '<B>BOLD!</B>'), '<I>BOLD!</I>')!
VALUES ASSERT_EQUALS(PCRE_SUB('Q(?!U)', '\0', 'QI'), 'Q')!

-- vim: set et sw=4 sts=4:
