CREATE TABLE FOO (
    ID INTEGER NOT NULL,
    VALUE INTEGER NOT NULL
)!

CREATE TABLE BAR LIKE FOO!
ALTER TABLE BAR ADD CONSTRAINT PK PRIMARY KEY (ID)!

INSERT INTO FOO VALUES
    (1, 2),
    (2, 4),
    (3, 8),
    (4, 16),
    (5, 32)!

CALL AUTO_MERGE('FOO', 'BAR', 'PK')!
VALUES ASSERT_EQUALS(5, (SELECT COUNT(*) FROM (SELECT * FROM FOO INTERSECT SELECT * FROM BAR) AS T))!

INSERT INTO FOO VALUES
    (6, 64),
    (7, 128)!

CALL AUTO_MERGE('FOO', 'BAR')!
VALUES ASSERT_EQUALS(7, (SELECT COUNT(*) FROM (SELECT * FROM FOO INTERSECT SELECT * FROM BAR) AS T))!

DELETE FROM FOO WHERE ID IN (1, 2)!

CALL AUTO_DELETE('FOO', 'BAR')!
VALUES ASSERT_EQUALS(5, (SELECT COUNT(*) FROM (SELECT * FROM FOO INTERSECT SELECT * FROM BAR) AS T))!

DELETE FROM FOO!

CALL AUTO_DELETE('FOO', 'BAR', 'PK')!
VALUES ASSERT_EQUALS(0, (SELECT COUNT(*) FROM BAR))!

DROP TABLE FOO!
DROP TABLE BAR!

-- vim: set et sw=4 sts=4:
