VALUES ASSERT_IS_NULL(UNICODE_REPLACE_BAD('FOO', NULL))!
VALUES ASSERT_IS_NULL(UNICODE_REPLACE_BAD(NULL, NULL))!
VALUES ASSERT_EQUALS(UNICODE_REPLACE_BAD('FOO', 'BAR'), 'FOO')!
VALUES ASSERT_EQUALS(UNICODE_REPLACE_BAD('FOO' || X'80', 'BAR'), 'FOOBAR')!
VALUES ASSERT_EQUALS(UNICODE_REPLACE_BAD(X'C2' || 'BAR', 'FOO'), 'FOOBAR')!

-- vim: set et sw=4 sts=4:
