CALL ASSERT_RAISES('70001', 'SIGNAL SQLSTATE ''70001''');

CALL ASSERT_RAISES(ASSERT_SQLSTATE, 'CALL ASSERT_RAISES(''70002'', ''SIGNAL SQLSTATE ''''70001''''''');

CALL ASSERT_RAISES(ASSERT_SQLSTATE, 'CALL ASSERT_RAISES(''70001'', ''SAVEPOINT FOO'')');

