CALL ASSERT_SIGNALS('70001', 'SIGNAL SQLSTATE ''70001''');

CALL ASSERT_SIGNALS(ASSERT_SQLSTATE, 'CALL ASSERT_SIGNALS(''70002'', ''SIGNAL SQLSTATE ''''70001''''''');

CALL ASSERT_SIGNALS(ASSERT_SQLSTATE, 'CALL ASSERT_SIGNALS(''70001'', ''SAVEPOINT FOO'')');

