CREATE TABLE FOO (
    ID INTEGER NOT NULL PRIMARY KEY,
    VALUE INTEGER NOT NULL
)!

CREATE TRIGGER FOO_UPDATE
    AFTER UPDATE ON FOO
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
BEGIN
    IF NEW.ID = NEW.VALUE THEN
        SIGNAL SQLSTATE '75000';
    END IF;
END!

CALL DISABLE_TRIGGER('FOO_UPDATE')!
VALUES ASSERT_EQUALS(0, (SELECT COUNT(*) FROM SYSCAT.TRIGGERS WHERE TRIGSCHEMA = CURRENT SCHEMA AND TRIGNAME = 'FOO_UPDATE'))!

CALL ENABLE_TRIGGER('FOO_UPDATE')!
VALUES ASSERT_TRIGGER_EXISTS('FOO_UPDATE')!

CALL DISABLE_TRIGGERS('FOO')!
VALUES ASSERT_EQUALS(0, (SELECT COUNT(*) FROM SYSCAT.TRIGGERS WHERE TRIGSCHEMA = CURRENT SCHEMA AND TRIGNAME = 'FOO_UPDATE'))!

CALL ENABLE_TRIGGERS('FOO')!
VALUES ASSERT_TRIGGER_EXISTS('FOO_UPDATE')!

DROP TABLE FOO!
